apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- ./manifests/cluster-role.yaml
- ./manifests/cluster-role-binding.yaml
- ./manifests/service-account.yaml
- ./manifests/deployment.yaml
- ./manifests/service.yaml