apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

resources:
- ./manifests/cluster-role.yaml
- ./manifests/cluster-role-binding.yaml
- ./manifests/service-account.yaml
- ./manifests/deployment.yaml
- ./manifests/service.yaml

images:
- name: registry.k8s.io/kube-state-metrics/kube-state-metrics
  newName: registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.15.0